"use client";
import { motion } from 'framer-motion';
import { Download, FileCheck2, Settings2, Share2, UploadCloud } from 'lucide-react';
const steps = [
  { icon: UploadCloud, number: '01', title: 'Choose your tool and file', text: 'Start with the task you need, then add the supported file or files.', tone: 'violet' },
  { icon: Settings2, number: '02', title: 'Fine-tune the result', text: 'Useful controls appear when you need them, with sensible defaults that keep the workflow simple.', tone: 'blue' },
  { icon: FileCheck2, number: '03', title: 'Stay informed while it works', text: 'A calm full-page progress view keeps each stage clear while your file is being prepared.', tone: 'green' },
  { icon: Download, number: '04', title: 'Download or share', text: 'When the result is ready, download it, share it when supported, or move straight to another task.', tone: 'blue' },
];
export function HowItWorks(){return <section className="relative mx-auto max-w-7xl px-4 py-20 md:px-8 md:py-28"><div className="max-w-3xl"><span className="ajn-section-kicker">Simple from start to finish</span><h2 className="mt-5 text-4xl font-black tracking-[-.04em] text-slate-950 md:text-6xl">A focused workflow for every file.</h2><p className="mt-5 text-base leading-7 text-slate-600">Choose a tool, make the adjustments that matter, follow clear progress and finish with an obvious next step.</p></div><div className="relative mt-12 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{steps.map(({icon:Icon,number,title,text,tone},index)=><motion.article key={title} initial={{opacity:0,y:14}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.05}} className="ajn-glass-card relative rounded-2xl p-6"><div className={`flex h-11 w-11 items-center justify-center rounded-xl ${tone==='violet'?'bg-violet-50 text-violet-600':tone==='green'?'bg-emerald-50 text-emerald-600':'bg-blue-50 text-blue-600'}`}><Icon className="h-5 w-5"/></div><p className="mt-6 text-[10px] font-black tracking-[.18em] text-slate-400">STEP {number}</p><h3 className="mt-2 text-lg font-black text-slate-950">{title}</h3><p className="mt-3 text-sm font-medium leading-6 text-slate-500">{text}</p>{index===3&&<div className="mt-4 flex gap-2 text-[10px] font-black text-blue-600"><Share2 className="h-3.5 w-3.5"/>Share when your device supports it</div>}</motion.article>)}</div></section>}
