"use client";
import Link from 'next/link';
import { motion, useReducedMotion } from 'framer-motion';
import { ArrowLeftRight, ArrowRight, FileText, ImageIcon } from 'lucide-react';
const categories=[
 {title:'Conversion',icon:ArrowLeftRight,tone:'blue',href:'/conversion-tools',description:'Move between PDF, image, text and supported document formats with focused conversion controls.',tools:[{label:'PDF to DOCX',href:'/pdf-to-docx'},{label:'DOCX to PDF',href:'/docx-to-pdf'}]},
 {title:'Image',icon:ImageIcon,tone:'green',href:'/image-tools',description:'Resize, crop, rotate, reduce and prepare images with simple tools built around common tasks.',tools:[{label:'Image to PDF',href:'/image-to-pdf'},{label:'PDF to PNG',href:'/pdf-to-png'}]},
 {title:'PDF',icon:FileText,tone:'violet',href:'/pdf-utilities',description:'Merge, split, organize, sign, protect, repair and refine PDF files from one consistent workspace.',tools:[{label:'Merge PDF',href:'/merge-pdf'},{label:'Protect PDF',href:'/protect-pdf'},{label:'Unlock PDF',href:'/unlock-pdf'}]}];
export function ToolCategories(){const reduceMotion=useReducedMotion();return <section className="mx-auto w-full max-w-7xl px-4 py-20 md:px-6 md:py-28 xl:px-8"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div className="max-w-3xl"><span className="ajn-section-kicker">Browse by task</span><h2 className="mt-5 text-[clamp(2.25rem,5vw,4rem)] font-black leading-[1.02] tracking-[-.04em] text-slate-950">Find the right workflow faster.</h2></div><Link href="/pdf-tools" className="inline-flex items-center gap-2 text-sm font-black text-blue-600 hover:text-blue-800">View all tools <ArrowRight className="h-4 w-4"/></Link></div><div className="mt-12 grid gap-5 md:grid-cols-3">{categories.map(({title,icon:Icon,tone,description,tools,href},index)=><motion.article key={title} initial={reduceMotion?false:{opacity:0,y:14}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.25}} transition={{delay:index*.05}} className="ajn-category-card"><div className={`ajn-white-icon-tile flex h-11 w-11 items-center justify-center rounded-xl ${tone==='violet'?'text-violet-600':tone==='green'?'text-emerald-600':'text-blue-600'}`}><Icon className="h-5 w-5"/></div><h3 className="mt-5 text-xl font-black text-slate-950">{title}</h3><p className="mt-3 min-h-[4.5rem] text-sm font-medium leading-6 text-slate-500">{description}</p><div className="mt-6 space-y-2 border-t border-slate-100 pt-5">{tools.map(tool=><Link key={tool.href} href={tool.href} className="flex min-h-10 items-center justify-between rounded-xl px-3 py-2 text-xs font-extrabold text-slate-700 hover:bg-blue-50 hover:text-blue-700"><span>{tool.label}</span><ArrowRight className="h-3.5 w-3.5"/></Link>)}</div><Link href={href} className="mt-5 inline-flex items-center gap-2 text-xs font-black text-blue-600 hover:text-blue-800">Browse {title.toLowerCase()} tools <ArrowRight className="h-3.5 w-3.5"/></Link></motion.article>)}</div></section>}
