"use client";
import Link from 'next/link';
import { ArrowRight, FileCheck2, KeyRound, ShieldCheck, Trash2 } from 'lucide-react';
const controls=[
 {icon:FileCheck2,title:'Input checks',text:'Supported file types, signatures and size limits are checked where the workflow requires them.'},
 {icon:KeyRound,title:'Authorized unlocking',text:'Unlock tools require the current valid password and an authorization confirmation.'},
 {icon:Trash2,title:'Temporary cleanup',text:'Server-assisted jobs use temporary request folders that are removed after delivery.'},
 {icon:ShieldCheck,title:'Documented policies',text:'Security and file-processing pages explain the safeguards and practical limitations in plain language.'},
];
export function TrustSecurity(){return <section className="mx-auto max-w-7xl px-4 py-20 md:px-8 md:py-28"><div className="overflow-hidden rounded-[1.8rem] border border-slate-200 bg-gradient-to-br from-slate-50 via-white to-blue-50 p-6 shadow-[0_28px_75px_rgba(37,62,113,.08)] md:p-10 lg:p-12"><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><span className="ajn-section-kicker">Practical safeguards</span><h2 className="mt-5 text-4xl font-black tracking-[-.04em] text-slate-950 md:text-6xl">Security information without homepage clutter.</h2><p className="mt-5 text-sm font-medium leading-7 text-slate-600">The main workspace stays simple. Detailed file-handling and security information remains available when you need to review it.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/security" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-slate-950 px-5 text-[11px] font-black text-white">Security practices <ArrowRight className="h-4 w-4"/></Link><Link href="/file-processing-policy" className="inline-flex min-h-11 items-center rounded-xl border border-slate-200 bg-white px-5 text-[11px] font-black text-slate-700">File processing policy</Link></div></div><div className="grid gap-4 sm:grid-cols-2">{controls.map(({icon:Icon,title,text})=><article key={title} className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><Icon className="h-4.5 w-4.5"/></span><h3 className="mt-4 text-sm font-black text-slate-950">{title}</h3><p className="mt-2 text-xs font-medium leading-5 text-slate-500">{text}</p></article>)}</div></div></div></section>}
