"use client";
import Link from 'next/link';
import { ArrowRight, FileCheck2, KeyRound, ShieldCheck, Trash2 } from 'lucide-react';
const controls=[
 {icon:FileCheck2,title:'Clear file checks',text:'AJN PDF validates supported file types and practical limits before a workflow begins.'},
 {icon:KeyRound,title:'Authorized access',text:'Protected-document tools require the information and confirmation needed for an authorized workflow.'},
 {icon:Trash2,title:'Automatic cleanup',text:'Files used for secure processing are removed after delivery according to the file-processing policy.'},
 {icon:ShieldCheck,title:'Policies you can review',text:'Security and file-handling details are available in plain language whenever you want the full picture.'},
];
export function TrustSecurity(){return <section className="mx-auto max-w-7xl px-4 py-20 md:px-8 md:py-28"><div className="relative overflow-hidden rounded-[1.8rem] border border-slate-200 bg-gradient-to-br from-slate-50 via-white to-blue-50 p-6 shadow-[0_28px_75px_rgba(37,62,113,.08)] md:p-10 lg:p-12"><div className="ajn-r8-security-wave" aria-hidden="true"/><div className="relative grid gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><span className="ajn-section-kicker">Professional safeguards</span><h2 className="mt-5 text-4xl font-black tracking-[-.04em] text-slate-950 md:text-6xl">A clean workspace, with the details available when you need them.</h2><p className="mt-5 text-sm font-medium leading-7 text-slate-600">AJN PDF keeps everyday document work simple while making privacy, security and file-handling information easy to find.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/security" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-slate-950 px-5 text-[11px] font-black text-white">Security practices <ArrowRight className="h-4 w-4"/></Link><Link href="/file-processing-policy" className="inline-flex min-h-11 items-center rounded-xl border border-slate-200 bg-white px-5 text-[11px] font-black text-slate-700">File handling details</Link></div></div><div className="grid gap-4 sm:grid-cols-2">{controls.map(({icon:Icon,title,text})=><article key={title} className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm"><span className="ajn-white-icon-tile flex h-10 w-10 items-center justify-center rounded-xl text-blue-600"><Icon className="h-4.5 w-4.5"/></span><h3 className="mt-4 text-sm font-black text-slate-950">{title}</h3><p className="mt-2 text-xs font-medium leading-5 text-slate-500">{text}</p></article>)}</div></div></div></section>}
