import { expect } from '@playwright/test';
import { chromium } from 'playwright';
import { PDFDocument } from 'pdf-lib';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import fs from 'node:fs';
import assert from 'node:assert/strict';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const production = process.argv.includes('--production');
const mode = production ? 'production' : 'development';
const out = path.join(root, 'test-results', mode);
fs.mkdirSync(out, {recursive:true});
const report = {mode, started:new Date().toISOString(), steps:[], pageErrors:[], consoleErrors:[], criticalRequests:[]};
const save = () => fs.writeFileSync(path.join(out,'editor-results.json'),JSON.stringify(report,null,2));
const log = fs.createWriteStream(path.join(out,'server.log'));
const env = {...process.env, NEXT_TELEMETRY_DISABLED:'1', AJN_ENABLE_HSTS:'false', NEXT_PUBLIC_PDF_BACKEND_URL:'http://127.0.0.1:8000'};
const server = spawn(process.execPath,['node_modules/next/dist/bin/next',production?'start':'dev','-H','127.0.0.1','-p','9002'],{cwd:root,env,stdio:['ignore','pipe','pipe']});
let browser, page;
const step = async(name, fn) => { try {console.log('RUN',name);const detail=await fn();report.steps.push({name,pass:true,...detail});save();console.log('PASS',name);}catch(e){report.steps.push({name,pass:false,error:e.message});save();throw e;} };
const fixture = name => path.join(root,'tests','fixtures',name);
const button = name => page.getByRole('button',{name,exact:true});
const ready = () => page.locator('[data-ajn-editor-shell][data-ajn-preview-ready="true"]').waitFor({timeout:50000});
const open = async(name) => {await page.locator('#ajn-edit-pdf-native-file-input').setInputFiles(fixture(name));await ready();};
const reopen = async(file) => {await button('Choose another PDF').click();await page.locator('#ajn-edit-pdf-native-file-input').setInputFiles(file);await ready();};
const download = async(name) => { const event=page.waitForEvent('download',{timeout:60000});await button('Download PDF').click();const file=path.join(out,name);await (await event).saveAs(file);assert.ok(fs.statSync(file).size>64);return file;};
const drag = async(locator,dx,dy) => { const b=await locator.boundingBox();assert.ok(b);const x=b.x+b.width/2,y=b.y+b.height/2;await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+dx,y+dy,{steps:8});await page.mouse.up();};
const hexRgb = hex => { const value=String(hex||'').replace('#',''); return value.length===6?[parseInt(value.slice(0,2),16),parseInt(value.slice(2,4),16),parseInt(value.slice(4,6),16)]:[0,0,0]; };
const rgbDistance = (a,b) => Math.hypot(a[0]-b[0],a[1]-b[1],a[2]-b[2]);
try {
 await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Server did not become ready')),60000);server.stdout.on('data',b=>{log.write(b);if(b.toString().includes('Ready in')){clearTimeout(timer);resolve();}});server.stderr.on('data',b=>log.write(b));server.on('exit',code=>{clearTimeout(timer);reject(Error(`Server exited ${code}`));});});
 const args = process.env.AJN_TEST_BROWSER_ARGS ? JSON.parse(process.env.AJN_TEST_BROWSER_ARGS) : [];
 browser = await chromium.launch({headless:true,executablePath:process.env.AJN_TEST_BROWSER_PATH || undefined,args});
 const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true});
 // Editor fixtures are synthetic; external document uploads are prohibited in this test.
 await context.route('**/*',route=>{const u=new URL(route.request().url());return ['localhost','127.0.0.1'].includes(u.hostname)||!u.protocol.startsWith('http')?route.continue():route.abort('blockedbyclient');});
 page=await context.newPage();page.setDefaultTimeout(45000);
 page.on('pageerror',e=>{report.pageErrors.push(e.stack||e.message);console.error('PAGEERROR',e.stack||e.message);});
 page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});
 page.on('requestfailed',r=>{if(/\/(?:pdf\.worker|pdfjs\/|ajn-ocr\/|_next\/static\/.*\.(?:js|css))/.test(r.url()) && r.failure()?.errorText!=='net::ERR_ABORTED')report.criticalRequests.push({url:r.url(),failure:r.failure()});});
 await step('cold first request returns 200',async()=>{const response=await page.goto('http://127.0.0.1:9002/edit-pdf',{waitUntil:'domcontentloaded',timeout:120000});assert.equal(response.status(),200);return {http:response.status()};});
 await step('digital upload, same-page editor and real preview',async()=>{await open('digital-3page.pdf');assert.ok(page.url().endsWith('/edit-pdf'));assert.equal(await page.locator('[data-ajn-edit-pdf-upload]').count(),0);const pixels=await page.locator('[data-ajn-pdf-preview-canvas]').evaluate(c=>{const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let dark=0;for(let i=0;i<d.length;i+=4)if(d[i]<100&&d[i+1]<100&&d[i+2]<100)dark++;return dark;});assert.ok(pixels>300,'Preview must contain text, not only a blank page');});
 await step('page navigation',async()=>{await page.locator('aside').first().getByRole('button',{name:'Page 2',exact:true}).click();await ready();await page.getByRole('button',{name:/Edit PDF text AJN TEST PAGE 2/}).waitFor();await page.locator('aside').first().getByRole('button',{name:'Page 1',exact:true}).click();await ready();});
 await step('zoom',async()=>{const c=page.locator('[data-ajn-pdf-preview-canvas]');const before=await c.evaluate(x=>x.width);await button('Zoom in').click();await ready();assert.ok(await c.evaluate(x=>x.width)>before);await button('Zoom out').click();await ready();});
 await step('select and edit original digital text',async()=>{await page.getByRole('button',{name:'Edit PDF text Original sample text',exact:true}).click();const input=page.locator('[data-editor-object="text"] textarea');await input.press('ControlOrMeta+A');await input.pressSequentially('Edited sample text',{delay:20});await input.press('Escape');await expect(page.locator('[data-editor-object="text"]').first()).toContainText('Edited sample text');});
 await step('add text',async()=>{await button('Add text').click();await page.locator('[data-ajn-pdf-preview-canvas]').click({position:{x:80,y:430}});const t=page.locator('[data-editor-object="text"] textarea');await t.press('ControlOrMeta+A');await t.pressSequentially('ADDED NOTE',{delay:20});await t.press('Escape');await expect(page.locator('[data-editor-object="text"]').last()).toContainText('ADDED NOTE');assert.equal(await page.locator('[data-editor-object="text"]').count(),2);});
 await step('add, move and resize image',async()=>{await page.locator('input[type=file]').setInputFiles(fixture('image.png'));const img=page.locator('[data-editor-object="image"]');await img.waitFor();await img.scrollIntoViewIfNeeded();const before=await img.boundingBox();await drag(img,60,25);const after=await img.boundingBox();assert.ok(Math.abs(after.x-before.x)>30);const initial=after.width;await drag(button('Resize selected object'),30,20);assert.ok((await img.boundingBox()).width>initial+10);});
 await step('delete image and undo/redo',async()=>{await button('Delete selected').click();assert.equal(await page.locator('[data-editor-object="image"]').count(),0);await button('Undo (Ctrl+Z)').click();assert.equal(await page.locator('[data-editor-object="image"]').count(),1);await button('Redo (Ctrl+Y)').click();assert.equal(await page.locator('[data-editor-object="image"]').count(),0);await button('Undo (Ctrl+Z)').click();});
 await step('rotate, reorder and delete page',async()=>{await button('Rotate page right').click();await ready();assert.equal(await page.locator('[data-ajn-editor-shell]').getAttribute('data-ajn-page-rotation'),'90');await button('Move page later').click();await button('Move page earlier').click();await page.locator('aside').first().getByRole('button',{name:'Page 3',exact:true}).click();await ready();await button('Delete page').click();assert.equal(await page.locator('aside').first().getByRole('button').count(),2);await page.locator('aside').first().getByRole('button',{name:'Page 1',exact:true}).click();await ready();await button('Rotate page left').click();await ready();});
 let digital;
 await step('export digital PDF',async()=>{await expect(page.locator('[data-editor-object="text"]').last()).toContainText('ADDED NOTE');digital=await download('digital-edited.pdf');const pdf=await PDFDocument.load(fs.readFileSync(digital));assert.equal(pdf.getPageCount(),2);return {bytes:fs.statSync(digital).size};});
 await step('reopen edited digital PDF',async()=>{
   await reopen(digital);
   const hits=page.locator('[data-source-text-hit="pdf"]');
   await hits.first().waitFor();
   const labels=await hits.evaluateAll(els=>els.map(e=>String(e.getAttribute('aria-label')||'').replace(/^Edit PDF text\s*/i,'')));
   const searchable=labels.join('').replace(/\s+/g,'').toUpperCase();
   assert.ok(searchable.includes('ADDEDNOTE'),'Reopened PDF must expose the added note through PDF text extraction');
   await page.screenshot({path:path.join(out,'digital-reopened.png')});
   return {searchableTextHits:labels.length};
 });
 await step('scan preview before OCR',async()=>{await button('Choose another PDF').click();await open('scan-1page.pdf');assert.equal(await page.locator('[data-source-text-hit="ocr"]').count(),0);assert.equal(await page.locator('script[data-ajn-tesseract]').count(),0);});
 await step('OCR recognizes actual scanned words',async()=>{await button('Scan current page for editable text').click();await page.locator('[data-source-text-hit="ocr"]').first().waitFor({timeout:120000});await button('Stop OCR').waitFor({state:'detached',timeout:120000}).catch(()=>{});const titles=await page.locator('[data-source-text-hit="ocr"]').evaluateAll(els=>els.map(e=>e.getAttribute('aria-label')));assert.ok(titles.some(t=>/TEST|Original|sample|Invoice|1250/i.test(t||'')),'OCR must recognize words, not just blank fallback regions');return {recognized:titles};});
 await step('select and edit OCR text',async()=>{const words=page.locator('[data-source-text-hit="ocr"]');let word=words.filter({hasText:'unused'});const original=await words.evaluateAll(els=>els.map(e=>e.getAttribute('aria-label')));const index=original.findIndex(t=>/sample/i.test(t||''));word=words.nth(index>=0?index:0);await word.click();const input=page.locator('[data-editor-object="text"] textarea');await input.press('Escape');await drag(button('Resize selected object'),100,0);await page.locator('[data-editor-object="text"]').dblclick();await input.press('ControlOrMeta+A');await input.pressSequentially('SCAN EDIT',{delay:20});await input.press('Escape');await expect(page.locator('[data-editor-object="text"]')).toContainText('SCAN EDIT');});
 let scanned;
 await step('export scanned PDF',async()=>{scanned=await download('scan-edited.pdf');const pdf=await PDFDocument.load(fs.readFileSync(scanned));assert.equal(pdf.getPageCount(),1);});
 await step('reopen scanned PDF and recognize exported edit',async()=>{await reopen(scanned);await button('Scan current page for editable text').click();await page.locator('[data-source-text-hit="ocr"]').first().waitFor({timeout:120000});await button('Stop OCR').waitFor({state:'detached',timeout:120000}).catch(()=>{});const text=await page.locator('[data-source-text-hit="ocr"]').evaluateAll(els=>els.map(e=>e.getAttribute('aria-label')).join(' '));assert.match(text,/SCAN|EDIT/i);await page.screenshot({path:path.join(out,'scan-reopened.png')});return {recognized:text};});
 await step('OCR replacement automatically matches font size weight and colour',async()=>{
   await button('Choose another PDF').click();
   await open('scan-style-1page.pdf');
   await button('Scan current page for editable text').click();
   await page.locator('[data-source-text-hit="ocr"]').first().waitFor({timeout:150000});
   await button('Stop OCR').waitFor({state:'detached',timeout:150000}).catch(()=>{});
   let hits=page.locator('[data-source-text-hit="ocr"]');
   let labels=await hits.evaluateAll(els=>els.map(e=>String(e.getAttribute('aria-label')||'')));
   const blueIndex=labels.findIndex(t=>/BLUE/i.test(t));
   assert.ok(blueIndex>=0,'Style fixture must OCR the BLUE word');
   await hits.nth(blueIndex).click();
   let object=page.locator('[data-editor-object="text"]').last();
   await object.waitFor();
   assert.equal(await object.getAttribute('data-ajn-auto-style'),'true');
   const family=await object.getAttribute('data-ajn-font-family');
   const size=Number(await object.getAttribute('data-ajn-font-size'));
   const color=await object.getAttribute('data-ajn-text-color');
   const weight=await object.getAttribute('data-ajn-font-weight');
   const scale=Number(await object.getAttribute('data-ajn-horizontal-scale'));
   assert.ok(family && family.length>1,'Auto match must choose a font family');
   assert.ok(size>=6 && size<=48,'Auto match must calculate a sensible source font size');
   assert.ok(scale>=0.70 && scale<=1.36,'Auto match horizontal scale must stay conservative');
   assert.ok(rgbDistance(hexRgb(color),[29,78,216])<125,`Blue source colour should remain blue-ish, got ${color}`);
   assert.equal(weight,'700','Bold source word should remain bold');
   const input=object.locator('textarea');
   await input.press('ControlOrMeta+A');
   await input.pressSequentially('BLUE REPLACEMENT VALUE THAT IS LONGER',{delay:5});
   const fittedSize=Number(await object.getAttribute('data-ajn-font-size'));
   assert.ok(fittedSize<=size+0.05,'Long replacement should auto-fit by shrinking, never enlarge past the matched source size');
   assert.equal(await object.getAttribute('data-ajn-auto-style'),'true');
   await input.press('Escape');
   hits=page.locator('[data-source-text-hit="ocr"]');
   labels=await hits.evaluateAll(els=>els.map(e=>String(e.getAttribute('aria-label')||'')));
   const whiteIndex=labels.findIndex(t=>/WHITE/i.test(t));
   assert.ok(whiteIndex>=0,'Style fixture must OCR the WHITE word');
   await hits.nth(whiteIndex).click();
   await page.waitForFunction(() => {
     const textarea=document.querySelector('[data-editor-object="text"][data-ajn-selected="true"] textarea');
     return textarea && /WHITE/i.test(String(textarea.value||''));
   },null,{timeout:5000});
   object=page.locator('[data-editor-object="text"][data-ajn-selected="true"]');
   await object.waitFor();
   const lightColor=await object.getAttribute('data-ajn-text-color');
   const light=hexRgb(lightColor);
   assert.ok((light[0]+light[1]+light[2])/3>165,`Light text on dark background must not be forced to black, got ${lightColor}`);
   await object.locator('textarea').press('Escape');
   hits=page.locator('[data-source-text-hit="ocr"]');
   labels=await hits.evaluateAll(els=>els.map(e=>String(e.getAttribute('aria-label')||'')));
   const italicIndex=labels.findIndex(t=>/Italic/i.test(t));
   assert.ok(italicIndex>=0,'Style fixture must OCR the Italic word');
   await hits.nth(italicIndex).click();
   await page.waitForFunction(() => {
     const textarea=document.querySelector('[data-editor-object="text"][data-ajn-selected="true"] textarea');
     return textarea && /Italic/i.test(String(textarea.value||''));
   },null,{timeout:5000});
   object=page.locator('[data-editor-object="text"][data-ajn-selected="true"]');
   await object.waitFor();
   const italicStyle=await object.getAttribute('data-ajn-font-style');
   const italicColor=await object.getAttribute('data-ajn-text-color');
   assert.equal(italicStyle,'italic','Italic source text should auto-match italic styling');
   assert.ok(rgbDistance(hexRgb(italicColor),[185,28,28])<125,`Red italic source colour should remain red-ish, got ${italicColor}`);
   await object.locator('textarea').press('Escape');
   await page.screenshot({path:path.join(out,'scan-style-auto-match.png')});
   return {family,size,color,weight,scale,fittedSize,light,italicStyle,italicColor};
 });
 await step('table scan detects editable cells',async()=>{await button('Choose another PDF').click();await open('scan-table-1page.pdf');await button('Scan + Table editing').click();const tableHits=page.locator('[data-source-text-hit="ocr"][data-table-cell="true"]');await tableHits.first().waitFor({timeout:180000});await button('Stop OCR').waitFor({state:'detached',timeout:180000}).catch(()=>{});const labels=await tableHits.evaluateAll(els=>els.map(e=>String(e.getAttribute('aria-label')||'')));const guides=await page.locator('[data-ajn-table-cell="true"]').count();assert.ok(tableHits && labels.length>=4,'Table mode must expose multiple editable table cells');assert.ok(guides>=4,'Detected table cells must have visual guides');assert.ok(labels.some(t=>/ITEM|QTY|RATE|AMOUNT|Apple|Rice|Milk|TOTAL|590/i.test(t)),'Table OCR must recognize real cell content');return {tableHits:labels.length,guides,labels};});
 await step('table cell text stays editable and does not cross its cell',async()=>{const tableHits=page.locator('[data-source-text-hit="ocr"][data-table-cell="true"]');const labels=await tableHits.evaluateAll(els=>els.map(e=>String(e.getAttribute('aria-label')||'')));const index=labels.findIndex(t=>/ITEM|Apple|Rice|Milk|TOTAL/i.test(t));const hit=tableHits.nth(index>=0?index:0);const row=await hit.getAttribute('data-table-row');const column=await hit.getAttribute('data-table-column');await hit.click();const object=page.locator('[data-editor-object="text"]');const input=object.locator('textarea');await input.waitFor();const before=await object.boundingBox();assert.ok(before);await input.press('ControlOrMeta+A');await input.pressSequentially('TABLE CELL EDITED VALUE',{delay:10});await input.press('Escape');await expect(object).toContainText('TABLE CELL EDITED VALUE');const after=await object.boundingBox();assert.ok(after);const cell=page.locator(`[data-ajn-table-cell="true"][data-table-row="${row}"][data-table-column="${column}"]`);const cellBox=await cell.boundingBox();assert.ok(cellBox);assert.ok(after.x+after.width<=cellBox.x+cellBox.width+4,'Edited table text must stay inside the detected cell width');return {row,column,beforeWidth:before.width,afterWidth:after.width,cellWidth:cellBox.width};});
 await step('table edit export remains a valid PDF',async()=>{const tablePdf=await download('table-edited.pdf');const pdf=await PDFDocument.load(fs.readFileSync(tablePdf));assert.equal(pdf.getPageCount(),1);assert.ok(fs.statSync(tablePdf).size>1000);return {bytes:fs.statSync(tablePdf).size};});
 await step('repeat route requests have no intermittent 500',async()=>{const codes=[];for(let i=0;i<4;i++)codes.push((await page.request.get('http://127.0.0.1:9002/edit-pdf')).status());assert.ok(codes.every(c=>c===200));return {codes};});
 await step('no fatal browser or critical request errors',async()=>{assert.deepEqual(report.pageErrors,[]);assert.deepEqual(report.criticalRequests,[]);assert.deepEqual(report.consoleErrors,[]);});
 report.pass=true;
} catch(error) {report.pass=false;report.failure=error.message;console.error(error.message);if(page)await page.screenshot({path:path.join(out,'failure.png'),timeout:10000}).catch(()=>{});process.exitCode=1;}
finally {report.finished=new Date().toISOString();save();server.kill('SIGTERM');await Promise.race([browser?.close(),new Promise(r=>setTimeout(r,2500))]);log.end();}
