import type { Metadata } from 'next';
import Link from 'next/link';
import { CheckCircle2, Crown } from 'lucide-react';
import { Navbar } from '@/components/landing/navbar';
import { MainFooter } from '@/components/landing/main-footer';
import { AJN_BILLING_URL, AJN_PLANS } from '@/lib/plans';

export const metadata: Metadata = { title: { absolute: 'AJN PDF Pricing - Free and Premium Plans' }, description: 'AJN PDF plan structure for Free, Premium and Business accounts.' };

export default function PricingPage(){return <div className="min-h-screen bg-white"><Navbar/><main className="pt-[96px] md:pt-[112px]"><section className="mx-auto max-w-7xl px-4 pb-10 text-center md:px-8"><Crown className="mx-auto h-8 w-8 text-violet-700"/><h1 className="mt-4 text-balance text-4xl font-black tracking-[-.05em] text-slate-950 md:text-6xl">Simple plans for PDF work.</h1><p className="mx-auto mt-4 max-w-2xl text-sm font-medium leading-7 text-slate-600 md:text-base">Core tools stay free. Premium is an entitlement layer for higher limits and cross-device features; the final price and checkout activate only when your billing provider is configured.</p></section><section className="mx-auto grid max-w-7xl gap-5 px-4 pb-16 md:grid-cols-3 md:px-8 md:pb-24">{AJN_PLANS.map(plan=><article key={plan.id} className={`relative rounded-[1.6rem] border p-6 shadow-sm ${plan.highlighted?'border-violet-300 bg-violet-50/50 shadow-violet-100':'border-slate-200 bg-white'}`}>{plan.highlighted?<span className="absolute right-4 top-4 rounded-full bg-violet-700 px-2.5 py-1 text-[9px] font-black uppercase tracking-wider text-white">Recommended</span>:null}<h2 className="text-2xl font-black tracking-tight text-slate-950">{plan.name}</h2><p className="mt-2 min-h-12 text-sm font-medium leading-6 text-slate-600">{plan.summary}</p><ul className="mt-6 space-y-3">{plan.features.map(feature=><li key={feature} className="flex gap-2 text-xs font-semibold leading-5 text-slate-700"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600"/>{feature}</li>)}</ul><div className="mt-7">{plan.id==='free'?<Link href="/pdf-tools" className="flex min-h-12 items-center justify-center rounded-xl border border-slate-200 bg-white px-4 text-xs font-black text-slate-800">Use Free tools</Link>:AJN_BILLING_URL?<a href={AJN_BILLING_URL} rel="noopener noreferrer" className="flex min-h-12 items-center justify-center rounded-xl bg-violet-700 px-4 text-xs font-black text-white shadow-lg shadow-violet-100 hover:bg-violet-800">Continue to billing</a>:<span className="flex min-h-12 items-center justify-center rounded-xl bg-slate-100 px-4 text-center text-[10px] font-black text-slate-500">Billing link not configured yet</span>}</div></article>)}</section></main><MainFooter/></div>}
