"use client";

import Link from 'next/link';
import { Code2, Crown, FileSignature, Laptop, LogOut, ShieldCheck, Smartphone, UserRound } from 'lucide-react';
import { Navbar } from '@/components/landing/navbar';
import { useAuth } from '@/lib/auth-context';

const products=[['AJN Desktop','/desktop',Laptop],['AJN Mobile','/mobile',Smartphone],['AJN Sign','/sign',FileSignature],['AJN API','/developers',Code2]] as const;

export default function AccountPage(){
  const auth=useAuth();
  const premiumUntil=auth.plan!=='free'&&auth.planValidUntil?new Date(auth.planValidUntil).toLocaleDateString():'';
  if(auth.loading)return <div className="min-h-screen bg-slate-50"><Navbar/><main className="mx-auto max-w-6xl px-4 pt-[120px]"><div className="h-40 animate-pulse rounded-2xl bg-slate-200"/></main></div>;
  if(!auth.session)return <div className="min-h-screen bg-slate-50"><Navbar/><main className="mx-auto max-w-xl px-4 pb-20 pt-[120px]"><div className="rounded-2xl border border-slate-200 bg-white p-7 text-center shadow-sm"><UserRound className="mx-auto h-10 w-10 text-violet-700"/><h1 className="mt-4 text-2xl font-black text-slate-950">Sign in to your AJN account</h1><p className="mt-3 text-sm font-medium leading-6 text-slate-600">Core PDF tools remain free without an account. Sign in for Premium entitlement and cross-product account features.</p><div className="mt-6 flex justify-center gap-3"><Link href="/login" className="rounded-xl bg-violet-700 px-5 py-3 text-xs font-black text-white">Sign in</Link><Link href="/signup" className="rounded-xl border border-slate-200 bg-white px-5 py-3 text-xs font-black text-slate-800">Create account</Link></div></div></main></div>;
  return <div className="min-h-screen bg-slate-50"><Navbar/><main className="mx-auto max-w-7xl px-4 pb-20 pt-[104px] md:px-8 md:pt-[120px]"><div className="grid gap-5 lg:grid-cols-[1fr_340px]"><section><div className="rounded-[1.6rem] border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.24em] text-violet-700">AJN Account</p><h1 className="mt-3 text-3xl font-black tracking-[-.04em] text-slate-950">{auth.session.displayName||auth.session.email}</h1><p className="mt-2 text-sm font-medium text-slate-500">{auth.session.email}</p>{premiumUntil?<p className="mt-2 text-xs font-black text-violet-700">Premium active through {premiumUntil} · no automatic renewal</p>:null}</div><span className={`inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-[10px] font-black ${auth.plan==='free'?'bg-slate-100 text-slate-700':'bg-violet-100 text-violet-800'}`}><Crown className="h-3.5 w-3.5"/>{auth.plan.toUpperCase()}</span></div><div className="mt-7 grid gap-3 sm:grid-cols-2">{products.map(([name,href,Icon])=><Link key={name} href={href} className="group flex items-center gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4 transition hover:border-violet-200 hover:bg-violet-50"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white text-violet-700 shadow-sm"><Icon className="h-5 w-5"/></span><span className="text-sm font-black text-slate-900">{name}</span></Link>)}</div></div></section><aside className="space-y-4"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><ShieldCheck className="h-5 w-5 text-emerald-600"/><h2 className="mt-3 text-sm font-black text-slate-950">Account privacy</h2><p className="mt-2 text-xs font-medium leading-5 text-slate-600">The account stores identity, billing entitlement and plan-expiry data. PDF contents are not added to your account profile by default.</p></div><Link href="/pricing" className="block rounded-2xl border border-violet-100 bg-violet-50 p-5"><Crown className="h-5 w-5 text-violet-700"/><h2 className="mt-3 text-sm font-black text-violet-950">Plans & Premium</h2><p className="mt-2 text-xs font-medium leading-5 text-violet-900/70">Purchase or extend verified 30-day or 365-day Premium access with Razorpay.</p></Link>{auth.claims.admin===true?<Link href="/admin" className="block rounded-2xl border border-slate-200 bg-white p-5 text-sm font-black text-slate-900">Admin analytics</Link>:null}<button onClick={auth.signOut} className="flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white text-xs font-black text-slate-700 hover:bg-slate-100"><LogOut className="h-4 w-4"/>Sign out</button></aside></div></main></div>;
}
